2024-04-01 20:48:08,486 | INFO | test_login.py: 25|------开始执行测试用例，开始时间为：2024-04-01 20:48:08------
2024-04-01 20:48:08,487 | INFO | mysql.py: 15|数据库查询结果为：{'id': 1, 'web': '急救云', 'key': 'url_api', 'value': 'http://systest.whsaviour.com/platform-admin'}
2024-04-01 20:48:08,487 | INFO | test_login.py: 82|正在执行正常登录用例
2024-04-01 20:48:08,487 | INFO | requests_utils.py: 7|发送请求的url为：http://systest.whsaviour.com/platform-admin/sys/login
2024-04-01 20:48:08,487 | INFO | requests_utils.py: 8|发送请求的method为：post
2024-04-01 20:48:08,487 | INFO | requests_utils.py: 9|发送请求的headers为：{'Content-Type': 'application/json'}
2024-04-01 20:48:08,488 | INFO | requests_utils.py: 10|发送请求的data为：{'username': 'admin', 'password': '10010.com'}
2024-04-01 20:48:08,575 | INFO | requests_utils.py: 23|响应状态码为：200
2024-04-01 20:48:08,576 | INFO | requests_utils.py: 24|响应success为：True
2024-04-01 20:48:08,576 | INFO | requests_utils.py: 25|响应message为：登录成功
2024-04-01 20:48:08,576 | INFO | test_login.py: 84|用例执行成功，请求的结果为：<Response [200]>
2024-04-01 20:48:08,576 | INFO | test_login.py: 91|relation为：，res_data为<Response [200]>
2024-04-01 20:48:08,636 | INFO | mysql.py: 15|数据库查询结果为：{'id': 1, 'web': '急救云', 'key': 'url_api', 'value': 'http://systest.whsaviour.com/platform-admin'}
2024-04-01 20:48:08,636 | INFO | test_login.py: 82|正在执行密码错误用例
2024-04-01 20:48:08,636 | INFO | requests_utils.py: 7|发送请求的url为：http://systest.whsaviour.com/platform-admin/sys/login
2024-04-01 20:48:08,636 | INFO | requests_utils.py: 8|发送请求的method为：post
2024-04-01 20:48:08,636 | INFO | requests_utils.py: 9|发送请求的headers为：{'Content-Type': 'application/json'}
2024-04-01 20:48:08,636 | INFO | requests_utils.py: 10|发送请求的data为：{'username': 'admin', 'password': '10010'}
2024-04-01 20:48:08,680 | INFO | requests_utils.py: 23|响应状态码为：200
2024-04-01 20:48:08,680 | INFO | requests_utils.py: 24|响应success为：False
2024-04-01 20:48:08,680 | INFO | requests_utils.py: 25|响应message为：用户名或密码错误
2024-04-01 20:48:08,680 | INFO | test_login.py: 84|用例执行成功，请求的结果为：<Response [200]>
2024-04-01 20:48:08,680 | INFO | test_login.py: 91|relation为：None，res_data为<Response [200]>
2024-04-01 20:48:08,689 | INFO | mysql.py: 15|数据库查询结果为：{'id': 1, 'web': '急救云', 'key': 'url_api', 'value': 'http://systest.whsaviour.com/platform-admin'}
2024-04-01 20:48:08,689 | INFO | test_login.py: 82|正在执行密码为空用例
2024-04-01 20:48:08,689 | INFO | requests_utils.py: 7|发送请求的url为：http://systest.whsaviour.com/platform-admin/sys/login
2024-04-01 20:48:08,689 | INFO | requests_utils.py: 8|发送请求的method为：post
2024-04-01 20:48:08,689 | INFO | requests_utils.py: 9|发送请求的headers为：{'Content-Type': 'application/json'}
2024-04-01 20:48:08,689 | INFO | requests_utils.py: 10|发送请求的data为：{'username': 'admin', 'password': ''}
2024-04-01 20:48:08,730 | INFO | requests_utils.py: 23|响应状态码为：200
2024-04-01 20:48:08,730 | INFO | requests_utils.py: 24|响应success为：False
2024-04-01 20:48:08,730 | INFO | requests_utils.py: 25|响应message为：用户名或密码错误
2024-04-01 20:48:08,730 | INFO | test_login.py: 84|用例执行成功，请求的结果为：<Response [200]>
2024-04-01 20:48:08,731 | INFO | test_login.py: 91|relation为：None，res_data为<Response [200]>
2024-04-01 20:48:08,740 | INFO | test_login.py: 28|------执行测试结束，完成时间为：2024-04-01 20:48:08------
2024-04-01 20:48:42,419 | INFO | test_login.py: 25|------开始执行测试用例，开始时间为：2024-04-01 20:48:42------
2024-04-01 20:48:42,421 | INFO | mysql.py: 15|数据库查询结果为：{'id': 1, 'web': '急救云', 'key': 'url_api', 'value': 'http://systest.whsaviour.com/platform-admin'}
2024-04-01 20:48:42,421 | INFO | test_login.py: 82|正在执行正常登录用例
2024-04-01 20:48:42,421 | INFO | requests_utils.py: 7|发送请求的url为：http://systest.whsaviour.com/platform-admin/sys/login
2024-04-01 20:48:42,422 | INFO | requests_utils.py: 8|发送请求的method为：post
2024-04-01 20:48:42,422 | INFO | requests_utils.py: 9|发送请求的headers为：{'Content-Type': 'application/json'}
2024-04-01 20:48:42,422 | INFO | requests_utils.py: 10|发送请求的data为：{'username': 'admin', 'password': '10010.com'}
2024-04-01 20:48:42,505 | INFO | requests_utils.py: 23|响应状态码为：200
2024-04-01 20:48:42,505 | INFO | requests_utils.py: 24|响应success为：True
2024-04-01 20:48:42,505 | INFO | requests_utils.py: 25|响应message为：登录成功
2024-04-01 20:48:42,506 | INFO | test_login.py: 84|用例执行成功，请求的结果为：<Response [200]>
2024-04-01 20:48:42,506 | INFO | test_login.py: 87|用例执行失败，请查看日志找原因。
2024-04-01 20:48:42,573 | INFO | mysql.py: 15|数据库查询结果为：{'id': 1, 'web': '急救云', 'key': 'url_api', 'value': 'http://systest.whsaviour.com/platform-admin'}
2024-04-01 20:48:42,573 | INFO | test_login.py: 82|正在执行密码错误用例
2024-04-01 20:48:42,573 | INFO | requests_utils.py: 7|发送请求的url为：http://systest.whsaviour.com/platform-admin/sys/login
2024-04-01 20:48:42,573 | INFO | requests_utils.py: 8|发送请求的method为：post
2024-04-01 20:48:42,573 | INFO | requests_utils.py: 9|发送请求的headers为：{'Content-Type': 'application/json'}
2024-04-01 20:48:42,574 | INFO | requests_utils.py: 10|发送请求的data为：{'username': 'admin', 'password': '10010'}
2024-04-01 20:48:42,628 | INFO | requests_utils.py: 23|响应状态码为：200
2024-04-01 20:48:42,628 | INFO | requests_utils.py: 24|响应success为：False
2024-04-01 20:48:42,628 | INFO | requests_utils.py: 25|响应message为：用户名或密码错误
2024-04-01 20:48:42,628 | INFO | test_login.py: 84|用例执行成功，请求的结果为：<Response [200]>
2024-04-01 20:48:42,628 | INFO | test_login.py: 87|用例执行失败，请查看日志找原因。
2024-04-01 20:48:42,636 | INFO | mysql.py: 15|数据库查询结果为：{'id': 1, 'web': '急救云', 'key': 'url_api', 'value': 'http://systest.whsaviour.com/platform-admin'}
2024-04-01 20:48:42,637 | INFO | test_login.py: 82|正在执行密码为空用例
2024-04-01 20:48:42,637 | INFO | requests_utils.py: 7|发送请求的url为：http://systest.whsaviour.com/platform-admin/sys/login
2024-04-01 20:48:42,637 | INFO | requests_utils.py: 8|发送请求的method为：post
2024-04-01 20:48:42,637 | INFO | requests_utils.py: 9|发送请求的headers为：{'Content-Type': 'application/json'}
2024-04-01 20:48:42,637 | INFO | requests_utils.py: 10|发送请求的data为：{'username': 'admin', 'password': ''}
2024-04-01 20:48:42,676 | INFO | requests_utils.py: 23|响应状态码为：200
2024-04-01 20:48:42,676 | INFO | requests_utils.py: 24|响应success为：False
2024-04-01 20:48:42,676 | INFO | requests_utils.py: 25|响应message为：用户名或密码错误
2024-04-01 20:48:42,677 | INFO | test_login.py: 84|用例执行成功，请求的结果为：<Response [200]>
2024-04-01 20:48:42,677 | INFO | test_login.py: 87|用例执行失败，请查看日志找原因。
2024-04-01 20:48:42,686 | INFO | test_login.py: 28|------执行测试结束，完成时间为：2024-04-01 20:48:42------
