2024-04-01 21:04:18,973 | INFO | test_login.py: 25|------开始执行测试用例，开始时间为：2024-04-01 21:04:18------
2024-04-01 21:04:18,975 | INFO | mysql.py: 15|数据库查询结果为：{'id': 1, 'web': '急救云', 'key': 'url_api', 'value': 'http://systest.whsaviour.com/platform-admin'}
2024-04-01 21:04:18,975 | INFO | test_login.py: 82|正在执行正常登录用例
2024-04-01 21:04:18,975 | INFO | requests_utils.py: 7|发送请求的url为：http://systest.whsaviour.com/platform-admin/sys/login
2024-04-01 21:04:18,975 | INFO | requests_utils.py: 8|发送请求的method为：post
2024-04-01 21:04:18,975 | INFO | requests_utils.py: 9|发送请求的headers为：{'Content-Type': 'application/json'}
2024-04-01 21:04:18,975 | INFO | requests_utils.py: 10|发送请求的data为：{'username': 'admin', 'password': '10010.com'}
2024-04-01 21:04:19,068 | INFO | requests_utils.py: 23|响应状态码为：200
2024-04-01 21:04:19,068 | INFO | requests_utils.py: 24|响应success为：True
2024-04-01 21:04:19,069 | INFO | requests_utils.py: 25|响应message为：登录成功
2024-04-01 21:04:19,069 | INFO | test_login.py: 84|用例执行成功，请求的结果为：True
2024-04-01 21:04:19,070 | INFO | test_login.py: 99|用例断言成功，预期结果为：True，实际结果为：True
2024-04-01 21:04:19,152 | INFO | mysql.py: 28|执行sql语句成功！语句为：insert into test_result_record(`case_id`, `times`, `response`, `result`) values ("1", "2024-04-01 21:04:19", "{'success': True, 'message': '登录成功', 'code': 200, 'result': {'multi_depart': 0, 'userInfo': {'id': 'e9ca23d68d884d4ebb19d07889727dae', 'username': 'admin', 'realname': '管理员', 'password': 'a2aa542a6313470b', 'salt': 'MT8T61Hf', 'avatar': 'user/20190119/logo-2_1547868176839.png', 'birthday': '2018-12-05', 'sex': 1, 'email': '11@qq.com', 'phone': '18566666661', 'orgCode': 'A01', 'status': 1, 'delFlag': '0', 'createBy': None, 'createTime': '2038-06-21 17:54:10', 'updateBy': 'admin', 'updateTime': '2024-03-22 17:10:37', 'activitiSync': '0'}, 'departs': [], 'token': 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE3MTE5ODM4NjEsInVzZXJuYW1lIjoiYWRtaW4ifQ.Op4oCrTd6PHb_41Iwycbq_mo0LIaqPyk62AkjV_WXjs'}, 'resultList': None, 'timestamp': 1711976661017}", "True") 
2024-04-01 21:04:19,187 | INFO | mysql.py: 15|数据库查询结果为：{'id': 1, 'web': '急救云', 'key': 'url_api', 'value': 'http://systest.whsaviour.com/platform-admin'}
2024-04-01 21:04:19,188 | INFO | test_login.py: 82|正在执行密码错误用例
2024-04-01 21:04:19,188 | INFO | requests_utils.py: 7|发送请求的url为：http://systest.whsaviour.com/platform-admin/sys/login
2024-04-01 21:04:19,188 | INFO | requests_utils.py: 8|发送请求的method为：post
2024-04-01 21:04:19,189 | INFO | requests_utils.py: 9|发送请求的headers为：{'Content-Type': 'application/json'}
2024-04-01 21:04:19,189 | INFO | requests_utils.py: 10|发送请求的data为：{'username': 'admin', 'password': '10010'}
2024-04-01 21:04:19,244 | INFO | requests_utils.py: 23|响应状态码为：200
2024-04-01 21:04:19,244 | INFO | requests_utils.py: 24|响应success为：False
2024-04-01 21:04:19,244 | INFO | requests_utils.py: 25|响应message为：用户名或密码错误
2024-04-01 21:04:19,245 | INFO | test_login.py: 84|用例执行成功，请求的结果为：False
2024-04-01 21:04:19,245 | INFO | test_login.py: 99|用例断言成功，预期结果为：False，实际结果为：False
2024-04-01 21:04:19,676 | INFO | mysql.py: 28|执行sql语句成功！语句为：insert into test_result_record(`case_id`, `times`, `response`, `result`) values ("2", "2024-04-01 21:04:19", "{'success': False, 'message': '用户名或密码错误', 'code': 500, 'result': None, 'resultList': None, 'timestamp': 1711976661232}", "True") 
2024-04-01 21:04:19,681 | INFO | mysql.py: 15|数据库查询结果为：{'id': 1, 'web': '急救云', 'key': 'url_api', 'value': 'http://systest.whsaviour.com/platform-admin'}
2024-04-01 21:04:19,682 | INFO | test_login.py: 82|正在执行密码为空用例
2024-04-01 21:04:19,682 | INFO | requests_utils.py: 7|发送请求的url为：http://systest.whsaviour.com/platform-admin/sys/login
2024-04-01 21:04:19,682 | INFO | requests_utils.py: 8|发送请求的method为：post
2024-04-01 21:04:19,682 | INFO | requests_utils.py: 9|发送请求的headers为：{'Content-Type': 'application/json'}
2024-04-01 21:04:19,682 | INFO | requests_utils.py: 10|发送请求的data为：{'username': 'admin', 'password': ''}
2024-04-01 21:04:19,735 | INFO | requests_utils.py: 23|响应状态码为：200
2024-04-01 21:04:19,736 | INFO | requests_utils.py: 24|响应success为：False
2024-04-01 21:04:19,736 | INFO | requests_utils.py: 25|响应message为：用户名或密码错误
2024-04-01 21:04:19,737 | INFO | test_login.py: 84|用例执行成功，请求的结果为：False
2024-04-01 21:04:19,738 | INFO | test_login.py: 99|用例断言成功，预期结果为：False，实际结果为：False
2024-04-01 21:04:19,826 | INFO | mysql.py: 28|执行sql语句成功！语句为：insert into test_result_record(`case_id`, `times`, `response`, `result`) values ("3", "2024-04-01 21:04:19", "{'success': False, 'message': '用户名或密码错误', 'code': 500, 'result': None, 'resultList': None, 'timestamp': 1711976661721}", "True") 
2024-04-01 21:04:19,830 | INFO | test_login.py: 28|------执行测试结束，完成时间为：2024-04-01 21:04:18------
