2024-04-01 19:30:32,657 | INFO | test_login.py: 25|------开始执行测试用例，开始时间为：2024-04-01 19:30:32------
2024-04-01 19:30:32,658 | INFO | mysql.py: 15|数据库查询结果为：{'id': 1, 'web': '急救云', 'key': 'url_api', 'value': 'http://systest.whsaviour.com/platform-admin'}
2024-04-01 19:30:32,658 | INFO | test_login.py: 82|正在执行正常登录用例，用例id为：1
2024-04-01 19:30:32,658 | INFO | requests_utils.py: 7|发送请求的url为：http://systest.whsaviour.com/platform-admin/sys/login
2024-04-01 19:30:32,658 | INFO | requests_utils.py: 8|发送请求的method为：post
2024-04-01 19:30:32,659 | INFO | requests_utils.py: 9|发送请求的headers为：{'Content-Type': 'application/json'}
2024-04-01 19:30:32,659 | INFO | requests_utils.py: 10|发送请求的data为：{'username': 'admin', 'password': '10010.com'}
2024-04-01 19:30:32,764 | INFO | requests_utils.py: 23|响应状态码为：200
2024-04-01 19:30:32,765 | INFO | requests_utils.py: 24|响应success为：True
2024-04-01 19:30:32,765 | INFO | requests_utils.py: 25|响应message为：登录成功
2024-04-01 19:30:32,765 | INFO | test_login.py: 85|用例执行成功，请求的结果为：None
2024-04-01 19:30:32,766 | INFO | test_login.py: 104|用例断言失败
2024-04-01 19:30:32,840 | INFO | mysql.py: 28|insert into test_result_record(`case_id`, `times`, `response`, `result`) values ("None", "2024-04-01 19:30:32", "False", "1") 
2024-04-01 19:30:32,899 | INFO | mysql.py: 15|数据库查询结果为：{'id': 1, 'web': '急救云', 'key': 'url_api', 'value': 'http://systest.whsaviour.com/platform-admin'}
2024-04-01 19:30:32,899 | INFO | test_login.py: 82|正在执行密码错误用例，用例id为：2
2024-04-01 19:30:32,899 | INFO | requests_utils.py: 7|发送请求的url为：http://systest.whsaviour.com/platform-admin/sys/login
2024-04-01 19:30:32,899 | INFO | requests_utils.py: 8|发送请求的method为：post
2024-04-01 19:30:32,899 | INFO | requests_utils.py: 9|发送请求的headers为：{'Content-Type': 'application/json'}
2024-04-01 19:30:32,899 | INFO | requests_utils.py: 10|发送请求的data为：{'username': 'admin', 'password': '10010'}
2024-04-01 19:30:32,939 | INFO | requests_utils.py: 23|响应状态码为：200
2024-04-01 19:30:32,939 | INFO | requests_utils.py: 24|响应success为：False
2024-04-01 19:30:32,939 | INFO | requests_utils.py: 25|响应message为：用户名或密码错误
2024-04-01 19:30:32,939 | INFO | test_login.py: 85|用例执行成功，请求的结果为：None
2024-04-01 19:30:32,939 | INFO | test_login.py: 104|用例断言失败
2024-04-01 19:30:33,014 | INFO | mysql.py: 28|insert into test_result_record(`case_id`, `times`, `response`, `result`) values ("None", "2024-04-01 19:30:32", "False", "2") 
2024-04-01 19:30:33,023 | INFO | mysql.py: 15|数据库查询结果为：{'id': 1, 'web': '急救云', 'key': 'url_api', 'value': 'http://systest.whsaviour.com/platform-admin'}
2024-04-01 19:30:33,023 | INFO | test_login.py: 82|正在执行密码为空用例，用例id为：3
2024-04-01 19:30:33,023 | INFO | requests_utils.py: 7|发送请求的url为：http://systest.whsaviour.com/platform-admin/sys/login
2024-04-01 19:30:33,023 | INFO | requests_utils.py: 8|发送请求的method为：post
2024-04-01 19:30:33,023 | INFO | requests_utils.py: 9|发送请求的headers为：{'Content-Type': 'application/json'}
2024-04-01 19:30:33,023 | INFO | requests_utils.py: 10|发送请求的data为：{'username': 'admin', 'password': ''}
2024-04-01 19:30:33,066 | INFO | requests_utils.py: 23|响应状态码为：200
2024-04-01 19:30:33,066 | INFO | requests_utils.py: 24|响应success为：False
2024-04-01 19:30:33,067 | INFO | requests_utils.py: 25|响应message为：用户名或密码错误
2024-04-01 19:30:33,067 | INFO | test_login.py: 85|用例执行成功，请求的结果为：None
2024-04-01 19:30:33,067 | INFO | test_login.py: 104|用例断言失败
2024-04-01 19:30:33,257 | INFO | mysql.py: 28|insert into test_result_record(`case_id`, `times`, `response`, `result`) values ("None", "2024-04-01 19:30:33", "False", "3") 
2024-04-01 19:30:33,264 | INFO | test_login.py: 28|------执行测试结束，完成时间为：2024-04-01 19:30:32------
