2024-04-01 19:52:20,593 | INFO | test_login.py: 25|------开始执行测试用例，开始时间为：2024-04-01 19:52:20------
2024-04-01 19:52:20,593 | INFO | mysql.py: 15|数据库查询结果为：{'id': 1, 'web': '急救云', 'key': 'url_api', 'value': 'http://systest.whsaviour.com/platform-admin'}
2024-04-01 19:52:20,594 | INFO | test_login.py: 82|正在执行正常登录用例
2024-04-01 19:52:20,594 | INFO | requests_utils.py: 7|发送请求的url为：http://systest.whsaviour.com/platform-admin/sys/login
2024-04-01 19:52:20,594 | INFO | requests_utils.py: 8|发送请求的method为：post
2024-04-01 19:52:20,594 | INFO | requests_utils.py: 9|发送请求的headers为：{'Content-Type': 'application/json'}
2024-04-01 19:52:20,595 | INFO | requests_utils.py: 10|发送请求的data为：{'username': 'admin', 'password': '10010.com'}
2024-04-01 19:52:20,697 | INFO | requests_utils.py: 23|响应状态码为：200
2024-04-01 19:52:20,698 | INFO | requests_utils.py: 24|响应success为：True
2024-04-01 19:52:20,698 | INFO | requests_utils.py: 25|响应message为：登录成功
2024-04-01 19:52:20,698 | INFO | test_login.py: 85|用例执行成功，请求的结果为：<Response [200]>
2024-04-01 19:52:20,812 | INFO | mysql.py: 28|insert into test_result_record(`case_id`, `times`, `response`, `result`) values ("<Response [200]>", "2024-04-01 19:52:20", "False", "1") 
2024-04-01 19:52:20,877 | INFO | mysql.py: 15|数据库查询结果为：{'id': 1, 'web': '急救云', 'key': 'url_api', 'value': 'http://systest.whsaviour.com/platform-admin'}
2024-04-01 19:52:20,877 | INFO | test_login.py: 82|正在执行密码错误用例
2024-04-01 19:52:20,877 | INFO | requests_utils.py: 7|发送请求的url为：http://systest.whsaviour.com/platform-admin/sys/login
2024-04-01 19:52:20,877 | INFO | requests_utils.py: 8|发送请求的method为：post
2024-04-01 19:52:20,877 | INFO | requests_utils.py: 9|发送请求的headers为：{'Content-Type': 'application/json'}
2024-04-01 19:52:20,877 | INFO | requests_utils.py: 10|发送请求的data为：{'username': 'admin', 'password': '10010'}
2024-04-01 19:52:20,915 | INFO | requests_utils.py: 23|响应状态码为：200
2024-04-01 19:52:20,916 | INFO | requests_utils.py: 24|响应success为：False
2024-04-01 19:52:20,916 | INFO | requests_utils.py: 25|响应message为：用户名或密码错误
2024-04-01 19:52:20,916 | INFO | test_login.py: 85|用例执行成功，请求的结果为：<Response [200]>
2024-04-01 19:52:21,049 | INFO | mysql.py: 28|insert into test_result_record(`case_id`, `times`, `response`, `result`) values ("<Response [200]>", "2024-04-01 19:52:20", "False", "2") 
2024-04-01 19:52:21,061 | INFO | mysql.py: 15|数据库查询结果为：{'id': 1, 'web': '急救云', 'key': 'url_api', 'value': 'http://systest.whsaviour.com/platform-admin'}
2024-04-01 19:52:21,061 | INFO | test_login.py: 82|正在执行密码为空用例
2024-04-01 19:52:21,061 | INFO | requests_utils.py: 7|发送请求的url为：http://systest.whsaviour.com/platform-admin/sys/login
2024-04-01 19:52:21,061 | INFO | requests_utils.py: 8|发送请求的method为：post
2024-04-01 19:52:21,061 | INFO | requests_utils.py: 9|发送请求的headers为：{'Content-Type': 'application/json'}
2024-04-01 19:52:21,062 | INFO | requests_utils.py: 10|发送请求的data为：{'username': 'admin', 'password': ''}
2024-04-01 19:52:21,102 | INFO | requests_utils.py: 23|响应状态码为：200
2024-04-01 19:52:21,102 | INFO | requests_utils.py: 24|响应success为：False
2024-04-01 19:52:21,102 | INFO | requests_utils.py: 25|响应message为：用户名或密码错误
2024-04-01 19:52:21,103 | INFO | test_login.py: 85|用例执行成功，请求的结果为：<Response [200]>
2024-04-01 19:52:21,375 | INFO | mysql.py: 28|insert into test_result_record(`case_id`, `times`, `response`, `result`) values ("<Response [200]>", "2024-04-01 19:52:21", "False", "3") 
2024-04-01 19:52:21,388 | INFO | test_login.py: 28|------执行测试结束，完成时间为：2024-04-01 19:52:20------
