2024-04-01 21:03:12,109 | INFO | test_login.py: 25|------开始执行测试用例，开始时间为：2024-04-01 21:03:12------
2024-04-01 21:03:12,110 | INFO | mysql.py: 15|数据库查询结果为：{'id': 1, 'web': '急救云', 'key': 'url_api', 'value': 'http://systest.whsaviour.com/platform-admin'}
2024-04-01 21:03:12,110 | INFO | test_login.py: 82|正在执行正常登录用例
2024-04-01 21:03:12,110 | INFO | requests_utils.py: 7|发送请求的url为：http://systest.whsaviour.com/platform-admin/sys/login
2024-04-01 21:03:12,110 | INFO | requests_utils.py: 8|发送请求的method为：post
2024-04-01 21:03:12,110 | INFO | requests_utils.py: 9|发送请求的headers为：{'Content-Type': 'application/json'}
2024-04-01 21:03:12,111 | INFO | requests_utils.py: 10|发送请求的data为：{'username': 'admin', 'password': '10010.com'}
2024-04-01 21:03:12,198 | INFO | requests_utils.py: 23|响应状态码为：200
2024-04-01 21:03:12,199 | INFO | requests_utils.py: 24|响应success为：True
2024-04-01 21:03:12,199 | INFO | requests_utils.py: 25|响应message为：登录成功
2024-04-01 21:03:12,199 | INFO | test_login.py: 84|用例执行成功，请求的结果为：True
2024-04-01 21:03:12,267 | INFO | mysql.py: 28|执行sql语句成功！语句为：insert into test_result_record(`case_id`, `times`, `response`, `result`) values ("1", "2024-04-01 21:03:12", "{'success': True, 'message': '登录成功', 'code': 200, 'result': {'multi_depart': 0, 'userInfo': {'id': 'e9ca23d68d884d4ebb19d07889727dae', 'username': 'admin', 'realname': '管理员', 'password': 'a2aa542a6313470b', 'salt': 'MT8T61Hf', 'avatar': 'user/20190119/logo-2_1547868176839.png', 'birthday': '2018-12-05', 'sex': 1, 'email': '11@qq.com', 'phone': '18566666661', 'orgCode': 'A01', 'status': 1, 'delFlag': '0', 'createBy': None, 'createTime': '2038-06-21 17:54:10', 'updateBy': 'admin', 'updateTime': '2024-03-22 17:10:37', 'activitiSync': '0'}, 'departs': [], 'token': 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE3MTE5ODM3OTQsInVzZXJuYW1lIjoiYWRtaW4ifQ.FmVGLawbRa6_9E306ub0TN8ITApT6VGEDOVUNEo5dg8'}, 'resultList': None, 'timestamp': 1711976594155}", "False") 
2024-04-01 21:03:12,355 | INFO | mysql.py: 15|数据库查询结果为：{'id': 1, 'web': '急救云', 'key': 'url_api', 'value': 'http://systest.whsaviour.com/platform-admin'}
2024-04-01 21:03:12,355 | INFO | test_login.py: 82|正在执行密码错误用例
2024-04-01 21:03:12,355 | INFO | requests_utils.py: 7|发送请求的url为：http://systest.whsaviour.com/platform-admin/sys/login
2024-04-01 21:03:12,355 | INFO | requests_utils.py: 8|发送请求的method为：post
2024-04-01 21:03:12,355 | INFO | requests_utils.py: 9|发送请求的headers为：{'Content-Type': 'application/json'}
2024-04-01 21:03:12,355 | INFO | requests_utils.py: 10|发送请求的data为：{'username': 'admin', 'password': '10010'}
2024-04-01 21:03:12,407 | INFO | requests_utils.py: 23|响应状态码为：200
2024-04-01 21:03:12,407 | INFO | requests_utils.py: 24|响应success为：False
2024-04-01 21:03:12,407 | INFO | requests_utils.py: 25|响应message为：用户名或密码错误
2024-04-01 21:03:12,408 | INFO | test_login.py: 84|用例执行成功，请求的结果为：False
2024-04-01 21:03:12,518 | INFO | mysql.py: 28|执行sql语句成功！语句为：insert into test_result_record(`case_id`, `times`, `response`, `result`) values ("2", "2024-04-01 21:03:12", "{'success': False, 'message': '用户名或密码错误', 'code': 500, 'result': None, 'resultList': None, 'timestamp': 1711976594397}", "False") 
2024-04-01 21:03:12,554 | INFO | mysql.py: 15|数据库查询结果为：{'id': 1, 'web': '急救云', 'key': 'url_api', 'value': 'http://systest.whsaviour.com/platform-admin'}
2024-04-01 21:03:12,554 | INFO | test_login.py: 82|正在执行密码为空用例
2024-04-01 21:03:12,554 | INFO | requests_utils.py: 7|发送请求的url为：http://systest.whsaviour.com/platform-admin/sys/login
2024-04-01 21:03:12,555 | INFO | requests_utils.py: 8|发送请求的method为：post
2024-04-01 21:03:12,555 | INFO | requests_utils.py: 9|发送请求的headers为：{'Content-Type': 'application/json'}
2024-04-01 21:03:12,555 | INFO | requests_utils.py: 10|发送请求的data为：{'username': 'admin', 'password': ''}
2024-04-01 21:03:12,599 | INFO | requests_utils.py: 23|响应状态码为：200
2024-04-01 21:03:12,600 | INFO | requests_utils.py: 24|响应success为：False
2024-04-01 21:03:12,600 | INFO | requests_utils.py: 25|响应message为：用户名或密码错误
2024-04-01 21:03:12,600 | INFO | test_login.py: 84|用例执行成功，请求的结果为：False
2024-04-01 21:03:12,668 | INFO | mysql.py: 28|执行sql语句成功！语句为：insert into test_result_record(`case_id`, `times`, `response`, `result`) values ("3", "2024-04-01 21:03:12", "{'success': False, 'message': '用户名或密码错误', 'code': 500, 'result': None, 'resultList': None, 'timestamp': 1711976594588}", "False") 
2024-04-01 21:03:12,693 | INFO | test_login.py: 28|------执行测试结束，完成时间为：2024-04-01 21:03:12------
2024-04-01 21:03:25,931 | INFO | test_login.py: 25|------开始执行测试用例，开始时间为：2024-04-01 21:03:25------
2024-04-01 21:03:25,932 | INFO | mysql.py: 15|数据库查询结果为：{'id': 1, 'web': '急救云', 'key': 'url_api', 'value': 'http://systest.whsaviour.com/platform-admin'}
2024-04-01 21:03:25,932 | INFO | test_login.py: 82|正在执行正常登录用例
2024-04-01 21:03:25,932 | INFO | requests_utils.py: 7|发送请求的url为：http://systest.whsaviour.com/platform-admin/sys/login
2024-04-01 21:03:25,932 | INFO | requests_utils.py: 8|发送请求的method为：post
2024-04-01 21:03:25,932 | INFO | requests_utils.py: 9|发送请求的headers为：{'Content-Type': 'application/json'}
2024-04-01 21:03:25,932 | INFO | requests_utils.py: 10|发送请求的data为：{'username': 'admin', 'password': '10010.com'}
2024-04-01 21:03:26,028 | INFO | requests_utils.py: 23|响应状态码为：200
2024-04-01 21:03:26,029 | INFO | requests_utils.py: 24|响应success为：True
2024-04-01 21:03:26,029 | INFO | requests_utils.py: 25|响应message为：登录成功
2024-04-01 21:03:26,029 | INFO | test_login.py: 84|用例执行成功，请求的结果为：True
2024-04-01 21:03:26,118 | INFO | mysql.py: 28|执行sql语句成功！语句为：insert into test_result_record(`case_id`, `times`, `response`, `result`) values ("1", "2024-04-01 21:03:26", "{'success': True, 'message': '登录成功', 'code': 200, 'result': {'multi_depart': 0, 'userInfo': {'id': 'e9ca23d68d884d4ebb19d07889727dae', 'username': 'admin', 'realname': '管理员', 'password': 'a2aa542a6313470b', 'salt': 'MT8T61Hf', 'avatar': 'user/20190119/logo-2_1547868176839.png', 'birthday': '2018-12-05', 'sex': 1, 'email': '11@qq.com', 'phone': '18566666661', 'orgCode': 'A01', 'status': 1, 'delFlag': '0', 'createBy': None, 'createTime': '2038-06-21 17:54:10', 'updateBy': 'admin', 'updateTime': '2024-03-22 17:10:37', 'activitiSync': '0'}, 'departs': [], 'token': 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE3MTE5ODM4MDcsInVzZXJuYW1lIjoiYWRtaW4ifQ.pLZGlmT_6GGWE52pUslPDQoWo9Qu6piY4yZriI1ilH0'}, 'resultList': None, 'timestamp': 1711976607986}", "False") 
2024-04-01 21:03:26,192 | INFO | mysql.py: 15|数据库查询结果为：{'id': 1, 'web': '急救云', 'key': 'url_api', 'value': 'http://systest.whsaviour.com/platform-admin'}
2024-04-01 21:03:26,192 | INFO | test_login.py: 82|正在执行密码错误用例
2024-04-01 21:03:26,192 | INFO | requests_utils.py: 7|发送请求的url为：http://systest.whsaviour.com/platform-admin/sys/login
2024-04-01 21:03:26,192 | INFO | requests_utils.py: 8|发送请求的method为：post
2024-04-01 21:03:26,193 | INFO | requests_utils.py: 9|发送请求的headers为：{'Content-Type': 'application/json'}
2024-04-01 21:03:26,193 | INFO | requests_utils.py: 10|发送请求的data为：{'username': 'admin', 'password': '10010'}
2024-04-01 21:03:26,235 | INFO | requests_utils.py: 23|响应状态码为：200
2024-04-01 21:03:26,236 | INFO | requests_utils.py: 24|响应success为：False
2024-04-01 21:03:26,236 | INFO | requests_utils.py: 25|响应message为：用户名或密码错误
2024-04-01 21:03:26,237 | INFO | test_login.py: 84|用例执行成功，请求的结果为：False
2024-04-01 21:03:26,351 | INFO | mysql.py: 28|执行sql语句成功！语句为：insert into test_result_record(`case_id`, `times`, `response`, `result`) values ("2", "2024-04-01 21:03:26", "{'success': False, 'message': '用户名或密码错误', 'code': 500, 'result': None, 'resultList': None, 'timestamp': 1711976608226}", "False") 
2024-04-01 21:03:26,374 | INFO | mysql.py: 15|数据库查询结果为：{'id': 1, 'web': '急救云', 'key': 'url_api', 'value': 'http://systest.whsaviour.com/platform-admin'}
2024-04-01 21:03:26,375 | INFO | test_login.py: 82|正在执行密码为空用例
2024-04-01 21:03:26,375 | INFO | requests_utils.py: 7|发送请求的url为：http://systest.whsaviour.com/platform-admin/sys/login
2024-04-01 21:03:26,375 | INFO | requests_utils.py: 8|发送请求的method为：post
2024-04-01 21:03:26,375 | INFO | requests_utils.py: 9|发送请求的headers为：{'Content-Type': 'application/json'}
2024-04-01 21:03:26,375 | INFO | requests_utils.py: 10|发送请求的data为：{'username': 'admin', 'password': ''}
2024-04-01 21:03:26,422 | INFO | requests_utils.py: 23|响应状态码为：200
2024-04-01 21:03:26,422 | INFO | requests_utils.py: 24|响应success为：False
2024-04-01 21:03:26,423 | INFO | requests_utils.py: 25|响应message为：用户名或密码错误
2024-04-01 21:03:26,423 | INFO | test_login.py: 84|用例执行成功，请求的结果为：False
2024-04-01 21:03:26,509 | INFO | mysql.py: 28|执行sql语句成功！语句为：insert into test_result_record(`case_id`, `times`, `response`, `result`) values ("3", "2024-04-01 21:03:26", "{'success': False, 'message': '用户名或密码错误', 'code': 500, 'result': None, 'resultList': None, 'timestamp': 1711976608410}", "False") 
2024-04-01 21:03:26,527 | INFO | test_login.py: 28|------执行测试结束，完成时间为：2024-04-01 21:03:25------
